# Generated by Django 3.2.12 on 2022-03-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220227_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date', 'status']},
        ),
    ]
