# Generated by Django 3.2.12 on 2022-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220520_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=True),
        ),
    ]
