# Generated by Django 3.2.12 on 2022-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_login_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
